- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.svg'
- name: LOGO
  value: 'https://static.tildacdn.com/tild3563-3735-4033-b839-386261353963/LOGOSCMblue.png'
- name: INSTALLATION_NAME
  value: 'Sport Casual Moscow'
- name: BRAND_URL
  value: 'https://www.chatwoot.com'
- name: WIDGET_BRAND_URL
  value: 'https://www.chatwoot.com'
- name: TERMS_URL
  value: 'https://www.chatwoot.com/terms-of-service'
- name: PRIVACY_URL
  value: 'https://www.chatwoot.com/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
- name: MAILER_INBOUND_EMAIL_DOMAIN
  value:
- name: MAILER_SUPPORT_EMAIL
  value:
- name: CREATE_NEW_ACCOUNT_FROM_DASHBOARD
  value: false
